#!/usr/bin/env bash

set -e



CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"
PLUGIN_DIR="plugins"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"

[[ -f zshenv ]] && . zshenv

git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"
git submodule update --init --recursive "${PLUGIN_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
    -d "${BASEDIR}" \
    --plugin-dir "${BASEDIR}/${PLUGIN_DIR}/*" \
    -c "${CONFIG}" \
    "${@}"
