format = '''
$character
'''

right_format = """$all"""

add_newline = true

palette = "tokyonight"

[palettes.tokyonight]
black = "#414868"
blue = "#7aa2f7"
cyan = "#7dcfff"
green = "#73daca"
purple = "#bb9af7"
red = "#f7768e"
white = "#c0caf5"
yellow = "#e0af68"
bright-black = "#414868"
bright-blue = "#7aa2f7"
bright-cyan = "#7dcfff"
bright-green = "#73daca"
bright-purple = "#bb9af7"
bright-red = "#f7768e"
bright-white = "#c0caf5"
bright-yellow = "#e0af68"

[character]
success_symbol = "[❯](bold black)[❯](bold white)"
error_symbol = "[❯](bold red)[❯](bold white)"

[directory]
style = "bold blue"
read_only = " "

[container]
style = "red bold dimmed"
