"$schema" = 'https://starship.rs/config-schema.json'

format = """
$fill$container$all\
$character
"""

add_newline = false
palette = "tokyonight"

[fill]
symbol = ' '

[character]
success_symbol = "[❯](bold black)[❯](bold bright-white)"
error_symbol = "[❯](bold red)[❯](bold bright-white)"

[directory]
style = "bold blue"
read_only = " "
truncation_length = 2
fish_style_pwd_dir_length = 1

[container]
style = "red bold dimmed"

[os]
disabled = true

[palettes.tokyonight]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
purple = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"
bright-black = "#444b6a"
bright-blue = "#7da6ff"
bright-cyan = "#0db9d7"
bright-green = "#b9f27c"
bright-purple = "#bb9af7"
bright-red = "#ff7a93"
bright-white = "#acb0d0"
bright-yellow = "#ff9e64"
