[settings]
experimental = true

[tools]
"aqua:bat" = "latest"
"aqua:eza" = "latest"
"aqua:fd" = "latest"
"aqua:lazygit" = "latest"
"aqua:ripgrep" = "latest"
"aqua:starship" = "latest"
"aqua:usage" = "latest"
