[tools]
azure-cli = "latest"
dive = "latest"
dotnet = "latest"
jq = "latest"
k3d = "latest"
kubectl = "latest"
mkcert = "latest"
python = "latest"
terraform = "latest"
terramate = "latest"
usage = "latest"
yq = "latest"

[settings]
experimental = true
env_file = ".env"
